apiVersion: apps/v1
kind: Deployment
metadata:
  name: concourse-ci-cd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: concourse-ci-cd
  template:
    metadata:
      labels:
        app: concourse-ci-cd
    spec:
      containers:
        - name: app
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          imagePullPolicy: Always