# Docker
docker-hub-email: harsh.vardhan@knoldus.com
docker-hub-username: harshrajput98
docker-hub-password: Rawat@123
docker-hub-repo-name: codeinsight

# Kubernetes
server: <<API SERVER URI>>
namespace: <<NAMESPACE>>
cad: <<CERT AUTH DATA>>
token: <<K8 TOKEN>>